name: bnbsmartchain

api:
  tier: api
  image: "shapeshiftdao/unchained-bnbsmartchain-api:latest"
  coinstack: node
  autoscaling: true
  replicas: 2
  max_replicas: 6
  cpu_threshold: 75
  limits:
    cpu: 1
    memory: 500Mi
  requests:
    cpu: 500m
    memory: 250Mi
  env:
  - name: INDEXER_URL
    value:
  - name: INDEXER_WS_URL
    value:
  - name: LOG_LEVEL
    value:
  - name: NETWORK
    value:
  - name: RPC_URL
    value:

statefulset:
  name: bnbsmartchain
  replicas: 2
  containers:
    - name: daemon
      image: "shapeshiftdao/bnb-smart-chain:v1.2.11"
      command: '/init.sh' 
      limits:
        cpu: 8
        memory: 72Gi
      requests:
        cpu: 4
        memory: 48Gi
      ports:
      - name: daemon-rpc
        containerPort: 8545
      - name: daemon-ws
        containerPort: 8546
      storage_size: 4500Gi
    - name: indexer
      image: "shapeshiftdao/unchained-blockbook:95ee9b5"
      command: {{ .Values.global.indexerCommand }}
      limits:
        cpu: 4
        memory: 24Gi
      requests:
        cpu: 2
      storage_size: 1000Gi