---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Chart.Name }}-sts
  namespace: {{ .Chart.Name }}
  labels: 
    {{- include "unchained.statefulsetLabels" . | nindent 4 }}
spec:
  serviceName: {{ .Chart.Name }}-svc
  replicas: {{ .Values.statefulset.replicas }}
  selector:
    matchLabels:   
      {{- include "unchained.statefulsetLabels" . | nindent 6 }}
  podManagementPolicy: 'Parallel'
  updateStrategy:
    type: 'RollingUpdate'
  template:
    metadata:
      namespace: {{ .Chart.Name }}
      labels:
        {{- include "unchained.statefulsetLabels" . | nindent 8 }}
    spec:
      containers: 
        {{- range .Values.statefulset.containers }}
        name: {{ .name }}
        image: {{ .image }}
        {{- with .env }}
        env: 
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{-with .ports }}
        ports: 
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .limits }}
        limits:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .requests }}
        requests:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        command: {{ tpl .command . }}
        startupProbe:
          failureThreshold: 60
          periodSeconds: 30
          timeoutSeconds: 10 
          exec:
            command: 
            - /startup.sh
          {{- if eq .name 'indexer' }}
          httpGet:
            path: '/api/v2'
            port: 8001
          {{- end }}
        livenessProbe:
          failureThreshold: 5
          periodSeconds: 30
          timeoutSeconds: 10
          exec:
            command: 
            - /liveness.sh
          {{- if eq .name 'indexer' }}
          httpGet:
            path: '/api/v2'
            port: 8001
          {{- end }}
        readinessProbe:
          failureThreshold: 10
          periodSeconds: 30
          timeoutSeconds: 10
          exec:
            command: 
            - /readiness.sh
        volumeMounts:
        - name: data-{{ $.Values.name }}
          mountPath: {{ default "/data" .dataDir }}
        - name: {{ $.Values.name }}
          mountPath: '/init.sh'
          subPath: {{ .name }}-init.sh
        - name: {{ $.Values.name }}
          mountPath: '/startup.sh'
          subPath: {{ .name }}-startup.sh
        - name: {{ $.Values.name }}
          mountPath: '/liveness.sh'
          subPath: {{ .name }}-liveness.sh
        - name: {{ $.Values.name }}
          mountPath: '/readiness.sh'
          subPath: {{ .name }}-readiness.sh
        {{- if eq .name 'daemon' }}
        - name: {{ $.Values.name }}
          mountPath: '/evm.sh'
          subPath: 'evm.sh'
        {{- else }}
        - name: {{ $.Values.name }}
          mountPath: '/indexer-config.json'
          subPath: 'indexer-config.json'
        {{ end }}
        {{ end }}
    terminationGracePeriodSeconds: 600
    volumes:
      - name: data
        persistentVolumeClaim:
          claimName:  
      - name: {{ .Values.name }}
        configMap:
          name: {{ .Chart.Name }}-scripts
          defaultMode: 0775
  volumeClaimTemplates:
  - metadata:
      name: 
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 