name: avalanche

api: 
  name: avalanche
  tier: api
  image: "shapeshiftdao/unchained-avalanche-api:latest"
  coinstack: node
  autoscaling: true
  replicas: 2
  max_replicas: 6
  cpu_threshold: 75
  env:
  - name: INDEXER_URL
    value:
  - name: INDEXER_WS_URL
    value:
  - name: LOG_LEVEL
    value:
  - name: NETWORK
    value:
  - name: RPC_URL
    value:

statefulset:
  name: avalanche
  replicas: 2
  containers:
    - name: daemon
      image: "avaplatform/avalanchego:v1.10.9"
      limits:
        cpu: 2
        memory: 12Gi
      requests:
        cpu: 1
      storage_size: 500Gi
      ports:
      - name: daemon-rpc
        containerPort: 9650
    - name: indexer
      image: "shapeshiftdao/unchained-blockbook:95ee9b5"
      command: {{ .Values.global.indexerCommand }}
      limits:
        cpu: 2
        memory: 6Gi
      requests:
        cpu: 1
      storage_size: 500Gi