apiVersion: v1
kind: Service
metadata:
  name: 
  namespace:
  labels:
spec:
  type: ClusterIP
  ports:
    - port: 
      targetPort: rpc
      protocol: TCP
      name: rpc
    - port: 3500
      targetPort: beacon
      protocol: TCP
      name: beacon
  selector: